In [3]:
from unittest.mock import inplace

import numpy as np
import pandas as pd
import matplotlib.pyplot as pl
import seaborn as sns

In [4]:
df = pd.read_csv('HousingData.csv')
display(df)

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [5]:
df.head()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
4,0.06905,0.0,2.18,0.0,0.458,7.147,54.2,6.0622,3,222,18.7,396.90,NaN,36.2

In [6]:
df.tail()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
501,0.06263,0.0,11.93,0.0,0.573,6.593,69.1,2.4786,1,273,21.0,391.99,NaN,22.4
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0
505,0.04741,0.0,11.93,0.0,0.573,6.030,NaN,2.5050,1,273,21.0,396.90,7.88,11.9

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 506 entries, 0 to 505
Data columns (total 14 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   CRIM     486 non-null    float64
 1   ZN       486 non-null    float64
 2   INDUS    486 non-null    float64
 3   CHAS     486 non-null    float64
 4   NOX      506 non-null    float64
 5   RM       506 non-null    float64
 6   AGE      486 non-null    float64
 7   DIS      506 non-null    float64
 8   RAD      506 non-null    int64
 9   TAX      506 non-null    int64
 10  PTRATIO  506 non-null    float64
 11  B        506 non-null    float64
 12  LSTAT    486 non-null    float64
 13  MEDV     506 non-null    float64
dtypes: float64(12), int64(2)
memory usage: 55.5 KB

In [8]:
df.describe()

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
count,486.000000,486.000000,486.000000,486.000000,506.000000,506.000000,486.000000,506.000000,506.000000,506.000000,506.000000,506.000000,486.000000,506.000000
mean,3.611874,11.211934,11.083992,0.069959,0.554695,6.284634,68.518519,3.795043,9.549407,408.237154,18.455534,356.674032,12.715432,22.532806
std,8.720192,23.388876,6.835896,0.255340,0.115878,0.702617,27.999513,2.105710,8.707259,168.537116,2.164946,91.294864,7.155871,9.197104
min,0.006320,0.000000,0.460000,0.000000,0.385000,3.561000,2.900000,1.129600,1.000000,187.000000,12.600000,0.320000,1.730000,5.000000
25%,0.081900,0.000000,5.190000,0.000000,0.449000,5.885500,45.175000,2.100175,4.000000,279.000000,17.400000,375.377500,7.125000,17.025000
50%,0.253715,0.000000,9.690000,0.000000,0.538000,6.208500,76.800000,3.207450,5.000000,330.000000,19.050000,391.440000,11.430000,21.200000
75%,3.560263,12.500000,18.100000,0.000000,0.624000,6.623500,93.975000,5.188425,24.000000,666.000000,20.200000,396.225000,16.955000,25.000000
max,88.976200,100.000000,27.740000,1.000000,0.871000,8.780000,100.000000,12.126500,24.000000,711.000000,22.000000,396.900000,37.970000,50.000000

In [9]:
df.columns

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [10]:
df.dtypes

CRIM       float64
ZN         float64
INDUS      float64
CHAS       float64
NOX        float64
RM         float64
AGE        float64
DIS        float64
RAD          int64
TAX          int64
PTRATIO    float64
B          float64
LSTAT      float64
MEDV       float64
dtype: object

In [11]:
df.keys()

Index(['CRIM', 'ZN', 'INDUS', 'CHAS', 'NOX', 'RM', 'AGE', 'DIS', 'RAD', 'TAX',
       'PTRATIO', 'B', 'LSTAT', 'MEDV'],
      dtype='object')

In [41]:
df.dropna(inplace=True)
df

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT,MEDV
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98,24.0
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14,21.6
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03,34.7
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94,33.4
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21,28.7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10,17.5
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33,16.8
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08,20.6
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64,23.9
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48,22.0

In [42]:
#x = pd.DataFrame(np.c_[df['lstat'] , df['rm']],columns=['lstat','rm'])
x = df.drop('MEDV',axis=1)
y = df['MEDV']

In [43]:
x

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
0,0.00632,18.0,2.31,0.0,0.538,6.575,65.2,4.0900,1,296,15.3,396.90,4.98
1,0.02731,0.0,7.07,0.0,0.469,6.421,78.9,4.9671,2,242,17.8,396.90,9.14
2,0.02729,0.0,7.07,0.0,0.469,7.185,61.1,4.9671,2,242,17.8,392.83,4.03
3,0.03237,0.0,2.18,0.0,0.458,6.998,45.8,6.0622,3,222,18.7,394.63,2.94
5,0.02985,0.0,2.18,0.0,0.458,6.430,58.7,6.0622,3,222,18.7,394.12,5.21
...,...,...,...,...,...,...,...,...,...,...,...,...,...
499,0.17783,0.0,9.69,0.0,0.585,5.569,73.5,2.3999,6,391,19.2,395.77,15.10
500,0.22438,0.0,9.69,0.0,0.585,6.027,79.7,2.4982,6,391,19.2,396.90,14.33
502,0.04527,0.0,11.93,0.0,0.573,6.120,76.7,2.2875,1,273,21.0,396.90,9.08
503,0.06076,0.0,11.93,0.0,0.573,6.976,91.0,2.1675,1,273,21.0,396.90,5.64
504,0.10959,0.0,11.93,0.0,0.573,6.794,89.3,2.3889,1,273,21.0,393.45,6.48

In [44]:
y

0      24.0
1      21.6
2      34.7
3      33.4
5      28.7
       ...
499    17.5
500    16.8
502    20.6
503    23.9
504    22.0
Name: MEDV, Length: 394, dtype: float64

In [45]:
x.shape

(394, 13)

In [46]:
from sklearn.model_selection import train_test_split
xtrain , xtest , ytrain , ytest = train_test_split(x,y,
                                                   random_state=0,
                                                   train_size=0.25)

In [47]:
xtrain

,CRIM,ZN,INDUS,CHAS,NOX,RM,AGE,DIS,RAD,TAX,PTRATIO,B,LSTAT
476,4.87141,0.0,18.10,0.0,0.614,6.484,93.6,2.3053,24,666,20.2,396.21,18.68
114,0.14231,0.0,10.01,0.0,0.547,6.254,84.2,2.2565,6,432,17.8,388.74,10.45
491,0.10574,0.0,27.74,0.0,0.609,5.983,98.8,1.8681,4,711,20.1,390.11,18.07
225,0.52693,0.0,6.20,0.0,0.504,8.725,83.0,2.8944,8,307,17.4,382.00,4.63
328,0.06617,0.0,3.24,0.0,0.460,5.868,25.8,5.2146,4,430,16.9,382.44,9.97
...,...,...,...,...,...,...,...,...,...,...,...,...,...
415,18.08460,0.0,18.10,0.0,0.679,6.434,100.0,1.8347,24,666,20.2,27.25,29.05
248,0.16439,22.0,5.86,0.0,0.431,6.433,49.1,7.8265,7,330,19.1,374.71,9.52
141,1.62864,0.0,21.89,0.0,0.624,5.019,100.0,1.4394,4,437,21.2,396.90,34.41
57,0.01432,100.0,1.32,0.0,0.411,6.816,40.5,8.3248,5,256,15.1,392.90,3.95
218,0.11069,0.0,13.89,1.0,0.550,5.951,93.8,2.8893,5,276,16.4,396.90,17.92

In [48]:
xtrain.shape

(98, 13)

In [49]:
from sklearn.linear_model import LinearRegression

In [50]:
regressor = LinearRegression()

In [51]:
regressor.fit(xtrain,ytrain)

LinearRegression()

In [52]:
regressor.coef_

array([ 1.75975218e-01,  7.77147682e-02,  2.60419256e-01,  6.33846719e+00,
       -2.93061382e+01,  5.82729546e+00, -5.37263281e-02, -1.90814475e+00,
        2.22346169e-01, -1.84787607e-02, -6.90415273e-01,  2.16025588e-02,
       -2.14000514e-01])

In [53]:
regressor.intercept_

np.float64(22.082718741685742)

In [55]:
y_pred = regressor.predict(xtest)

In [56]:
y_pred

array([18.13421236, 18.28733097, 26.87837986, 43.56379343, 15.92755481,
       18.86949427, 30.52886468, 18.8454982 , 28.63092191, 13.80088065,
       22.81920539, 14.56838531, 23.50123077, 26.44263288,  7.8511206 ,
       33.24047581, 27.30102889, 28.87927318, 25.06698774, 28.97400458,
       18.89930863, 31.00124269, 20.95113574, 19.22140024, 19.99894217,
       23.44632338, 20.87698289, 25.94521905, 23.96560489, 25.15405914,
        4.72826494, 27.01642978, 18.07773051, 26.34296027, 15.8532341 ,
       15.53025731, 22.35979007, 17.58849618, 22.53400917, 12.4374363 ,
       24.18575233, 14.37704968, 32.79538269, 22.88844748, 34.1081181 ,
       13.26891517, 21.72014732, 17.32507934,  9.98582497, 16.46063827,
       19.83451052, 18.43444927, 12.45520486, 34.1586355 , 20.76429967,
       21.44965762, 18.6407481 , 17.60168441, 21.13549763, 28.60903074,
       17.7075007 , 19.85533163, 21.01455154, 18.5676957 , 21.72916782,
       44.14285629, 18.74430969, 30.07950388, 15.38604656, 32.36291588,
       22.03250147,  7.14115419, 26.51983381, 17.42225361, 18.09502378,
       12.70837769, 23.84661923, 31.72266747, 13.06311553, 35.25662867,
       35.71537941, 20.47755484, 11.41674704, 19.93410657, 26.88639383,
       19.05356211, 31.08115673, 46.45833916, 28.52226216, 23.02353248,
       24.11459335, 36.79758295, 25.46693863, 22.21884788, 21.01561494,
       22.54316709, 24.27410932, 18.90944656, 25.62963125, 39.0721293 ,
       24.51664717, 18.55006056, 28.29890977, 11.84558705, 28.80940311,
       17.57724344, 31.57528247, 20.40986227, 28.37219895, 20.15993165,
       22.46061963, 15.67891367, 41.8048723 , 36.07164711, 27.67604129,
       37.63924624, 14.33262519, 20.09124835, 15.32869778, 36.00714248,
       33.11943345, 24.47716862, 33.00227733, 23.04290475, 29.20420012,
       30.3703344 , 20.7146428 , 26.91256014, 11.23841125, 11.85643784,
        3.59164199, 17.13485657, 24.03910646, 27.96780741, 13.59156014,
       21.91950678, 32.87762815, 25.25351848, 35.35605562, 28.36751497,
       29.92408943, 18.81128763, 14.00444687,  8.71553582,  6.32635485,
       20.28068732, 17.74358427, 25.97990082, 22.68082735,  6.42091302,
       11.76848452, 23.24562688, 24.97945208, 22.76920034, 34.09302667,
       27.08073524, 37.41688838, 43.01359014, 20.18923229, 24.80406347,
       25.37640219, 28.37115315, 25.6352482 , 19.22947107, 41.85590223,
       25.73851507, 21.84767457, 24.6715389 , 18.71156432, 32.1577477 ,
       31.1615554 , 23.41551384, 20.92974229, 21.94818061, 23.95309378,
       12.50042817, 14.07051279, 12.0698067 , 15.47898739, 16.859944  ,
        5.41034697, 16.18012159, 16.78387688, 30.5997514 , 34.83296055,
       33.84324973, 40.87974118, 20.73507839, 16.20854899, 22.79940184,
       52.63122578, 33.09780695, 27.37426143, 13.02254545, 27.72876577,
       30.44730439, 20.72005303, 22.33412341, 19.20713696, 20.75376134,
       17.5661608 , 20.13962093, 33.68823207, 20.37113979, 13.60191138,
       22.98716065, 26.55737665, 18.36336133, 11.92213381, 17.21440729,
       17.90820159, 29.5910785 , 35.44779666, 24.54245713, 25.4798604 ,
       16.89828468,  9.30640836, 42.66984745, 10.58610847, 20.28845788,
       29.52888414, 27.02721445, 40.14342659, 37.38046007, 13.6699498 ,
       22.89228212, 18.51965915, 18.75686526, 27.90112031, 42.02308936,
       14.42002262, 21.16188311, 24.69313679, 35.96787504, 35.43237616,
       12.95092233, 22.23126147, 30.49745167, 21.11497776, 17.76937314,
       32.85714937, 18.62202805, 20.58845933, 26.87718924, 18.36945624,
       23.03473939, 19.78059103, 15.61909698, 24.55565029, 33.16546441,
       29.93007137, 21.11798557, 24.8681925 , 25.2710528 , 33.12026929,
       17.73807946, 13.70984832, 14.28339741, 37.23656969, 11.1162165 ,
       27.53495477, 12.89971278, 22.67786056, 26.01316148, 23.99265679,
       39.7279246 , 20.63421957,  8.22898146, 38.16076873, 17.74651415,
       27.87393812, 21.39845964, 18.37466283, 23.66355252, 25.81754812,
       20.41648347, 26.4971369 , 19.64729868, 18.1323292 , 17.59930516,
       14.68673652, 16.87374671, 38.15184078, 19.30669792, 15.2652557 ,
       10.57302613, 13.05365837, 35.61221229, 26.90585293, 22.98789541,
       35.94464287, 23.93700214, 14.21139437, 28.37619442, 27.02237428,
       33.44124247])

In [57]:
y_pred.shape

(296,)

In [58]:
result = pd.DataFrame({'Actual' : ytest , 'Predicted' : y_pred})
result

     Actual  Predicted
136    17.4  18.134212
360    25.0  18.287331
81     23.9  26.878380
195    50.0  43.563793
421    14.2  15.927555
..      ...        ...
242    22.2  23.937002
27     14.8  14.211394
52     25.0  28.376194
0      24.0  27.022374
258    36.0  33.441242

[296 rows x 2 columns]

In [60]:
residual_err = abs(ytest - y_pred)
residual_err

136    0.734212
360    6.712669
81     2.978380
195    6.436207
421    1.727555
         ...
242    1.737002
27     0.588606
52     3.376194
0      3.022374
258    2.558758
Name: MEDV, Length: 296, dtype: float64

In [61]:
sum(residual_err)/len(residual_err)

3.858015766723094

In [66]:
from sklearn.metrics import mean_absolute_error
mean_absolute_error(ytest,y_pred)

3.8580157667230948

In [64]:
from sklearn.metrics import mean_absolute_percentage_error
mean_absolute_percentage_error(ytest,y_pred)

0.22758755777607692

In [67]:
regressor.score(xtest,ytest)

0.6316244536004998

In [68]:
from sklearn.metrics import r2_score
r2_score(ytest,y_pred)

0.6316244536004998

In [81]:
new = [[.658,0,8.7584,0,0.757,5.742387,69.5,3.587,4,307,22,49.99,11.4]]
new_data = {k : v for k,v in zip(xtrain.columns,*new)}
df_new = pd.DataFrame(new_data,index=pd.interval_range(start=0,end=len(new)))

In [82]:
regressor.predict(df_new)

array([3.84628572])