In [1]:
import pandas as pd
import numpy as np
from sklearn import datasets
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
age_group = np.array([
"18-25","18-25","18-25","18-25","18-25","18-25","18-25","18-25",
"26-35","26-35","26-35","26-35","26-35","26-35","26-35","26-35",
"36-45","36-45","36-45","36-45","36-45","36-45","36-45","36-45",
"46-60","46-60","46-60","46-60","46-60","46-60","46-60","46-60",
"61-75","61-75","61-75","61-75","61-75","61-75",
"76-100","76-100","76-100","76-100"
])

income = np.array([
3.2,4.1,2.8,3.6,np.nan,4.5,3.9,2.5,
6.5,7.2,np.nan,8.0,6.9,7.5,9.1,6.2,
10.5,11.2,9.8,np.nan,12.1,10.9,11.5,13.0,
14.5,15.2,13.8,16.1,np.nan,15.4,14.9,16.5,
12.2,11.8,np.nan,10.5,12.9,11.4,
8.1,np.nan,7.5,6.8
])

data = dict()
data['age_grp'] = age_group
data['income'] = np.round(income * 100000,2)

In [3]:
df = pd.DataFrame(data,index=range(0,42,1))

In [4]:
df.index.name = 'Sr No.'
df

       age_grp     income
Sr No.
0        18-25   320000.0
1        18-25   410000.0
2        18-25   280000.0
3        18-25   360000.0
4        18-25        NaN
5        18-25   450000.0
6        18-25   390000.0
7        18-25   250000.0
8        26-35   650000.0
9        26-35   720000.0
10       26-35        NaN
11       26-35   800000.0
12       26-35   690000.0
13       26-35   750000.0
14       26-35   910000.0
15       26-35   620000.0
16       36-45  1050000.0
17       36-45  1120000.0
18       36-45   980000.0
19       36-45        NaN
20       36-45  1210000.0
21       36-45  1090000.0
22       36-45  1150000.0
23       36-45  1300000.0
24       46-60  1450000.0
25       46-60  1520000.0
26       46-60  1380000.0
27       46-60  1610000.0
28       46-60        NaN
29       46-60  1540000.0
30       46-60  1490000.0
31       46-60  1650000.0
32       61-75  1220000.0
33       61-75  1180000.0
34       61-75        NaN
35       61-75  1050000.0
36       61-75  1290000.0
37       61-75  1140000.0
38      76-100   810000.0
39      76-100        NaN
40      76-100   750000.0
41      76-100   680000.0

In [5]:
df.isnull().sum()

age_grp    0
income     6
dtype: int64

In [6]:
df.fillna({'income':df['income'].mean()},
          inplace = True)
df.isnull().sum()

age_grp    0
income     0
dtype: int64

In [7]:
np.round(df['income'].agg(['mean','median','min','max','std']),2)

mean       951666.67
median     951666.67
min        250000.00
max       1650000.00
std        381175.97
Name: income, dtype: float64

In [8]:
grp = df.groupby('age_grp')
grp

In [9]:
for name,group in grp['income']:
    print(name,group)

18-25 Sr No.
0    320000.000000
1    410000.000000
2    280000.000000
3    360000.000000
4    951666.666667
5    450000.000000
6    390000.000000
7    250000.000000
Name: income, dtype: float64
26-35 Sr No.
8     650000.000000
9     720000.000000
10    951666.666667
11    800000.000000
12    690000.000000
13    750000.000000
14    910000.000000
15    620000.000000
Name: income, dtype: float64
36-45 Sr No.
16    1.050000e+06
17    1.120000e+06
18    9.800000e+05
19    9.516667e+05
20    1.210000e+06
21    1.090000e+06
22    1.150000e+06
23    1.300000e+06
Name: income, dtype: float64
46-60 Sr No.
24    1.450000e+06
25    1.520000e+06
26    1.380000e+06
27    1.610000e+06
28    9.516667e+05
29    1.540000e+06
30    1.490000e+06
31    1.650000e+06
Name: income, dtype: float64
61-75 Sr No.
32    1.220000e+06
33    1.180000e+06
34    9.516667e+05
35    1.050000e+06
36    1.290000e+06
37    1.140000e+06
Name: income, dtype: float64
76-100 Sr No.
38    810000.000000
39    951666.666667
40    750000.000000
41    680000.000000
Name: income, dtype: float64

In [10]:
np.round(grp['income'].agg(['mean','median','min','max','std']),2)

               mean     median        min         max        std
age_grp
18-25     426458.33   375000.0  250000.00   951666.67  222433.22
26-35     761458.33   735000.0  620000.00   951666.67  118995.26
36-45    1106458.33  1105000.0  951666.67  1300000.00  115677.57
46-60    1448958.33  1505000.0  951666.67  1650000.00  218248.69
61-75    1138611.11  1160000.0  951666.67  1290000.00  121702.81
76-100    797916.67   780000.0  680000.00   951666.67  115449.00

In [11]:
num_list = grp['income'].apply(list).to_list()
num_list

[[320000.0,
  410000.0,
  280000.0,
  360000.0,
  951666.6666666666,
  450000.0,
  390000.0,
  250000.0],
 [650000.0,
  720000.0,
  951666.6666666666,
  800000.0,
  690000.0,
  750000.0,
  910000.0,
  620000.0],
 [1050000.0,
  1120000.0,
  980000.0,
  951666.6666666666,
  1210000.0,
  1090000.0,
  1150000.0,
  1300000.0],
 [1450000.0,
  1520000.0,
  1380000.0,
  1610000.0,
  951666.6666666666,
  1540000.0,
  1490000.0,
  1650000.0],
 [1220000.0, 1180000.0, 951666.6666666666, 1050000.0, 1290000.0, 1140000.0],
 [810000.0, 951666.6666666666, 750000.0, 680000.0]]

In [12]:
iris_df = sns.load_dataset('iris')

In [13]:
iris_df

     sepal_length  sepal_width  petal_length  petal_width    species
0             5.1          3.5           1.4          0.2     setosa
1             4.9          3.0           1.4          0.2     setosa
2             4.7          3.2           1.3          0.2     setosa
3             4.6          3.1           1.5          0.2     setosa
4             5.0          3.6           1.4          0.2     setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  virginica
146           6.3          2.5           5.0          1.9  virginica
147           6.5          3.0           5.2          2.0  virginica
148           6.2          3.4           5.4          2.3  virginica
149           5.9          3.0           5.1          1.8  virginica

[150 rows x 5 columns]

In [14]:
iris_df.shape

(150, 5)

In [15]:
iris_df.describe()

       sepal_length  sepal_width  petal_length  petal_width
count    150.000000   150.000000    150.000000   150.000000
mean       5.843333     3.057333      3.758000     1.199333
std        0.828066     0.435866      1.765298     0.762238
min        4.300000     2.000000      1.000000     0.100000
25%        5.100000     2.800000      1.600000     0.300000
50%        5.800000     3.000000      4.350000     1.300000
75%        6.400000     3.300000      5.100000     1.800000
max        7.900000     4.400000      6.900000     2.500000

In [16]:
iris_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   sepal_length  150 non-null    float64
 1   sepal_width   150 non-null    float64
 2   petal_length  150 non-null    float64
 3   petal_width   150 non-null    float64
 4   species       150 non-null    str
dtypes: float64(4), str(1)
memory usage: 6.0 KB

In [17]:
iris_df['species'].value_counts()

species
setosa        50
versicolor    50
virginica     50
Name: count, dtype: int64

In [18]:
iris_grp = iris_df.groupby('species')

In [19]:
num_cols = iris_df.select_dtypes(include=['float64']).columns.to_list()

In [24]:
for cols in num_cols:
    display(iris_grp[cols].agg([lambda x : x.quantile(0.75),'mean','std','min','max']).rename(columns={'<lambda_0>':'75%ile'}))

            75%ile   mean       std  min  max
species
setosa         5.2  5.006  0.352490  4.3  5.8
versicolor     6.3  5.936  0.516171  4.9  7.0
virginica      6.9  6.588  0.635880  4.9  7.9

            75%ile   mean       std  min  max
species
setosa       3.675  3.428  0.379064  2.3  4.4
versicolor   3.000  2.770  0.313798  2.0  3.4
virginica    3.175  2.974  0.322497  2.2  3.8

            75%ile   mean       std  min  max
species
setosa       1.575  1.462  0.173664  1.0  1.9
versicolor   4.600  4.260  0.469911  3.0  5.1
virginica    5.875  5.552  0.551895  4.5  6.9

            75%ile   mean       std  min  max
species
setosa         0.3  0.246  0.105386  0.1  0.6
versicolor     1.5  1.326  0.197753  1.0  1.8
virginica      2.3  2.026  0.274650  1.4  2.5